### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by namnatulco** [pstjohn/circadian-methods#1]
I stumbled upon your repository looking for a pyplot implementation of bagplots and would like to re-use your code (with attribution, obviously), but I didn't see any license file. Is it OK with you if I just re-use and re-publish the file with a link back to your repository?

The project I'd like to use your code in will be under an [apache 2.0 license](http://www.apache.org/licenses/LICENSE-2.0), and I'd basically use your script to plot graphs that will probably end up in a paper later on.

**Comment by pstjohn** [comment]
Of course, you're welcome to whatever's in here. What license would you want this to be released under? would MIT work? I'm happy to add one.

**Comment by namnatulco** [comment]
MIT would be fine for me. I have no specific preference, I would probably reference this issue and leave it at that, but any of the open source non-copyleft licenses should work for me.

I've noticed that there was a missing import, so I added some code to a copy of your file and referenced the project github page and this issue for now.

Thanks!

**Comment by pstjohn** [comment]
No problem! I can't really speak to the code quality at this point, this repo is mainly a dump of all my phd-related files :)

License is added now.

**Comment by namnatulco** [comment]
yeah, I might have a pull request for you later depending on whether I will actually use bag plots at all, turns out they're generally not fantastic with the data I current have, since I have too few points :) thanks for sharing though!
